mainapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from mainapp.views import MainSearch

app_name='mainapp'

urlpatterns = (
    path('home/', MainSearch, name='mainapp'),

)

postapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from postapp.views import PostCreateView, PostDeleteView, PostDetailView, PostListView

app_name = 'postapp'

urlpatterns = [
    path('create/', PostCreateView.as_view(), name='create'),
    path('delete/<int:pk>', PostDeleteView.as_view(), name='delete'),
    path('detail/<int:pk>', PostDetailView.as_view(), name='detail'),
    path('list/', PostListView.as_view(), name='list'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

yoleejolee/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

app_name = 'postapp'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('mainapp.urls')),
    path('post/', include('postapp.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/models.py
from django.db import models

# Create your models here.

from django.db import models

# Create your models here.

class Mainhome(models.Model):
    search_text = models.CharField(max_length=200, null=True)

postapp/models.py
from django.contrib.auth.models import User
from django.db import models
from django import forms


class Post(models.Model):

    recipe_type = models.CharField(max_length=200, null=True)
    recipe_material = models.CharField(max_length=200, null=True)

    title = models.CharField(max_length=200, null=True)
    image = models.ImageField(upload_to='', null=False)
    content = models.TextField(null=True)

    created_at = models.DateField(auto_now_add=True, null=True)

postapp/forms.py
from django.forms import ModelForm

from postapp.models import Post




class PostCreationForm(ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'image', 'content']

class CommentCreationForm(ModelForm):
    class Meta:
        model = Post
        fields = ['content']

mainapp/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import ListView

import postapp.models


def MainSearch(request) :
    return render(request, 'articleapp/list.html')

class PostListView(ListView):
    model = postapp.models.Post
    context_object_name = 'Post_list'
    template_name = 'postapp/list.html'
    paginate_by = 10

postapp/views.py
import json

from django.http import request
from django.shortcuts import render

# Create your views here.
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView, ListView
from django.urls import reverse, reverse_lazy
from django.views.generic.edit import FormMixin

from postapp.forms import PostCreationForm, CommentCreationForm
from postapp.models import Post


class PostCreateView(CreateView):
    model = Post
    form_class = PostCreationForm
    template_name = 'postapp/create.html'

    def form_valid(self, form):
        temp_article = form.save(commit=False)
        temp_article.recipe_type = self.request.POST.getlist('food[]')
        temp_article.recipe_material = self.request.POST.getlist('Ingredients[]')
        temp_article.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('postapp:detail', kwargs={'pk': self.object.pk})



class PostDeleteView(DeleteView):
    model = Post
    context_object_name = 'target_article'
    success_url = reverse_lazy('postapp:list')
    template_name = 'postapp/delete.html'


class PostDetailView(DetailView, FormMixin):
    model = Post
    form_class = PostCreationForm
    context_object_name = 'target_post'
    template_name = 'postapp/detail.html'

class PostListView(ListView):
    model = Post
    context_object_name = 'post_list'
    template_name = 'postapp/list.html'
    paginate_by = 10

articleapp/templates/articleapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

  <div style="text-align: center; max-width: 500px; margin: 4rem auto">
    <div class="mb-4">
      <h4>Article Create</h4>
    </div>
    <form action="{% url 'articleapp:create' %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
    </form>
  </div>

{% endblock %}

mainapp/templates/articleapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

  <div style="text-align: center; max-width: 500px; margin: 4rem auto">
    <div class="mb-4">
      <h4>Article Create</h4>
    </div>
    <form action="{% url 'articleapp:create' %}" method="get" enctype="multipart/form-data">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
    </form>
  </div>

{% endblock %}

mainapp/templates/articleapp/delete.html
{% extends 'base.html' %}

{% block content %}

  <div style="text-align: center; max-width: 500px; margin: 4rem auto">
    <div class="mb-4">
      <h4>Delete Article : {{ target_article.title }}</h4>
    </div>
    <form action="{% url 'articleapp:delete' pk=target_article.pk %}" method="post">
      {% csrf_token %}
      <input type="submit" class="btn btn-danger rounded-pill col-6 mt-3">
    </form>
  </div>

{% endblock %}

mainapp/templates/articleapp/detail.html
{% extends 'base.html' %}


{% block content %}

    <div>
        <div style="text-align: center; max-width: 700px; margin: 4rem auto;">

            <h1>
                {{ target_article.title }}
            </h1>
            <h5>
                {{ target_article.writer.profile.nickname }}
            </h5>
            <hr>

            <img style="width: 100%; border-radius: 1rem; margin: 2rem 0;"
                    src="{{ target_article.image.url }}" alt="">

            <p>
                {{ target_article.content }}
            </p>

            {% if target_article.writer == user %}
            <a href="{% url 'articleapp:update' pk=target_article.pk %}"
            class="btn btn-primary rounded-pill col-3">
                Update
            </a>
            <a href="{% url 'articleapp:delete' pk=target_article.pk %}"
            class="btn btn-danger rounded-pill col-3">
                Delete
            </a>
            {% endif %}
            <hr>

            {% for comment in target_article.comment.all %}
                {% include 'commentapp/detail.html' with comment=comment %}
            {% endfor %}

            {% include 'commentapp/create.html' with article=target_article %}

        </div>
    </div>


{% endblock %}

mainapp/templates/articleapp/list.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<style>

    .container {
        padding: 0;
        margin: 0;
    }
    .container a {
        width: 45%;
        max-width: 250px;
    }

    .container div {
        display: flex;
        justify-content: center;
        align-items: center;
        border-radius: 1rem;
    }

    .container img {
        width: 100%;
        border-radius: 1rem;

    }
</style>

<br>

<form action="." method="post"> {% csrf_token %}
    {{ form.as_table }}
    <div style=" text-align:center">
        <h4>요리 이름으로 검색</h4>
        <input type="검색" value="" style="width:300px;height:50px;font-size:30px;">
        <button type="submit" style="width:120px;height:50px;font-size:30px;background-color:#69F0AE">검색</button>
    </div>
    <hr>
    {% include 'articleapp/listTemplate.html' %}
    <hr>

    <div class="container">

    {% for post in post_list %}
    <a href="{% url 'postapp:detail' pk=post.pk %}">
        #{% include 'snippets/card.html' with article=article %}
    </a>
    {% endfor %}
</div>
<script src="{% static 'js/magicgrid.js' %}"></script>

</form>
{% endblock %}

mainapp/templates/articleapp/listTemplate.html
<form method="get" action="form-action.html" >
    <div style=" text-align:center" >
        <h4>재료로 검색</h4>
            <fieldset>
                <h5>음식 종류 선택</h5>
                전체<input type="radio" name="food" value="all" checked />
                한식<input type="radio" name="food" value="korea" />
                중식<input type="radio" name="food" value="china" />
                양식<input type="radio" name="food" value="usa" />
            </fieldset>
            <fieldset>
                <legend>재료 선택</legend>
                파 <input type="checkbox" name="Ingredients" value="exercise" />
                양파 <input type="checkbox" name="Ingredients" value="movie" />
                당근 <input type="checkbox" name="Ingredients" value="music" />
                햄 <input type="checkbox" name="Ingredients" value="ect" />
                감자 <input type="checkbox" name="Ingredients" value="ect" />
                <br>
                계란 <input type="checkbox" name="Ingredients" value="ect" />
                버섯 <input type="checkbox" name="Ingredients" value="ect" />
                돼지고기 <input type="checkbox" name="Ingredients" value="ect" />
                소고기 <input type="checkbox" name="Ingredients" value="ect" />
                닭고기 <input type="checkbox" name="Ingredients" value="ect" />
                <br>
                숙주나물 <input type="checkbox" name="Ingredients" value="ect" />
                콩나물 <input type="checkbox" name="Ingredients" value="ect" />
                시금치 <input type="checkbox" name="Ingredients" value="ect" />
                브로콜리 <input type="checkbox" name="Ingredients" value="ect" />
                 <p><input type="submit" value="Submit"> <input type="reset" value="Reset"></p>
            </fieldset>
    </div>
        </form>
    <hr>

mainapp/templates/articleapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

  <div style="text-align: center; max-width: 500px; margin: 4rem auto">
    <div class="mb-4">
      <h4>Article Update</h4>
    </div>
    <form action="{% url 'articleapp:update' pk=target_article.pk %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
    </form>
  </div>

{% endblock %}

postapp/templates/postapp/CreateList.html
<div style="text-align:center" class="form-check">
            <h4></h4>
                <fieldset>
                    <h5>음식 종류 선택</h5>
                    전체<input type="radio" name="food[]" value="전체" checked />
                    한식<input type="radio" name="food[]" value="한식" />
                    중식<input type="radio" name="food[]" value="중식" />
                    양식<input type="radio" name="food[]" value="양식" />
                </fieldset>
                <fieldset>
                    <legend>재료 선택</legend>
                    파 <input type="checkbox" name="Ingredients[]" value="파"/>
                    양파 <input type="checkbox" name="Ingredients[]" value="양파" />
                    당근 <input type="checkbox" name="Ingredients[]" value="당근" />
                    햄 <input type="checkbox" name="Ingredients[]" value="햄" />
                    감자 <input type="checkbox" name="Ingredients[]" value="감자" />
                    <br>
                    계란 <input type="checkbox" name="Ingredients[]" value="계란" />
                    버섯 <input type="checkbox" name="Ingredients[]" value="버섯" />
                    돼지고기 <input type="checkbox" name="Ingredients[]" value="돼지고기" />
                    소고기 <input type="checkbox" name="Ingredients[]" value="소고기" />
                    닭고기 <input type="checkbox" name="Ingredients[]" value="닭고기" />
                    <br>
                    숙주나물 <input type="checkbox" name="Ingredients[]" value="숙주나물" />
                    콩나물 <input type="checkbox" name="Ingredients[]" value="콩나물" />
                    시금치 <input type="checkbox" name="Ingredients[]" value="시금치" />
                    브로콜리 <input type="checkbox" name="Ingredients[]" value="브로콜리" />
                </fieldset>
</div>

postapp/templates/postapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

  <div style="text-align: center; max-width: 500px; margin: 4rem auto">
    <div class="mb-4">
      <h4>레시피 작성</h4>
    </div>
    <form action="{% url 'postapp:create' %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {% bootstrap_form form %}

      <hr>
      {% include 'postapp/CreateList.html' %}
      <hr>
      <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
    </form>
  </div>


{% endblock %}

postapp/templates/postapp/delete.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <div style="text-align:center; max-width: 400px; margin:4rem auto">
        <div class="mb-4">
            <h4>Delete Article : {{ target_article.title }}</h4>
        </div>
        <form action="{% url 'postapp:delete' pk=target_delete.pk %}" method="post">
            {% csrf_token %}

            <input type="submit" class="btn btn-danger rounded-pill col-6 mt-3">
        </form>
    </div>


{% endblock %}

postapp/templates/postapp/detail.html
{% extends 'base.html' %}


{% block content %}
    <div>
        <div style="text-align: center; max-width: 700px; margin: 4rem auto;">

            <h1>
                {{ target_post.title }}
            </h1>
            <h2>
                요리종류 : {{ target_post.recipe_type}}
                <br>
                들어간 재료 :{{ target_post.recipe_material}}
            </h2>
            <hr>

            <img style="width: 100%; border-radius: 1rem; margin: 2rem 0;"
                   src = {{ target_post.image.url }}>
            <p>
                {{ target_post.content }}
            </p>

            <hr>

        </div>
    </div>


{% endblock %}

postapp/templates/postapp/list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<style>

    .container {
        padding: 0;
        margin: 0;
    }
    .container a {
        width: 45%;
        max-width: 250px;
    }

    .container div {
        display: flex;
        justify-content: center;
        align-items: center;
        border-radius: 1rem;
    }

    .container img {
        width: 30%;
        border-radius: 1rem;

    }
</style>
{% if post_list %}
<div class="container">

    {% for post in post_list %}
    <a href="{% url 'postapp:detail' pk=post.pk %}">
        <img src="{{post.image.url}}">
    </a>
    {% endfor %}
</div>
<script src="{% static 'js/magicgrid.js' %}"></script>

{% else %}
<div class="text-center">
    <h1>No Article YET!</h1>
</div>
{% endif %}

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="ko">

{% include 'head.html' %}

<body style="font-family: 'NanumSquareR';">

    {% include 'header.html' %}

    <hr>

    {% block content %}
    {% endblock %}

    <hr>

    {% include 'footer.html' %}

</body>
</html>

templates/footer.html
<div class="Jichuuu_footer">
    <div style="text-align: center;">
        <nav>
        <a href='https://underdogrev.notion.site/965bbf2508584da6bf599f58f095bfc2'>Notion</a> |
            <span>E-mail : rlghks131@korea.ac.kr</span>
    </nav>
        <p>
        <span>Underdog Revolution TEAM :: YORIZORI(김기환,정하은,현지수)</span><br/>
        <span>Copyright 2022. YORIZORI. All Rights Reserved.</span>
    </p>
    </div>
</div>

templates/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>I want Sleep</title>

    <!--  BOOTSTRAP LINK  -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <!-- GOOGLE FONTS LINK    -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Gamja+Flower&display=swap" rel="stylesheet">

    <!-- DEFAULT CSS LINK -->
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">

    <style>
        @font-face {
            font-family: 'NanumSquareR';
            src: local('NanumSquareR'),
            url("{% static 'fonts/NanumSquareR.ttf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareEB';
            src: local('NanumSquareEB'),
            url("{% static 'fonts/NanumSquareEB.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareB';
            src: local('NanumSquareB'),
            url("{% static 'fonts/NanumSquareB.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareR';
            src: local('NanumSquareR'),
            url("{% static 'fonts/NanumSquareR.otf' %}") format("opentype");
        }
    </style>

</head>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

templates/header.html
 <div class="Jichuuu_header">
        <div style="text-align: center">
             <h1 class="Jichuuu_logo">요리조리</h1>
        </div>
    </div>

templates/snippets/card.html
<div>
    <img src="{{ article.image.url }}" alt="">
</div>

templates/snippets/card_project.html
<div style="display: block; text-align: center">
    <img src="{{ project.image.url }}" alt="">
    <h5 class="mt-2" style="font-family: 'NanumSquareE';">
        {{ project.title ㅣ truncatechars:8 }}
    </h5>
</div>

templates/snippets/list_fragment.html
{% load static %}

{% block content %}

<style>

      .container {
        padding: 0;
        margin 0, auto;
      }

      .container a {
       width: 45%;
       max-width: 250px;
      }

      .container div {
      display: flex;
      justify-content: center;
      align-items: center;
      border-radius: 8px;

      border-radius: 1rem;
    }

    .container img {
      width: 100%;
      border-radius: 1rem;
    }

</style>
    {% if article_list %}
    <div class="container">
      {% for article in article_list %}
      <a href="{% url 'articleapp:detail' pk=article.pk %}">
        {% include 'snippets/card.html' with article=article %}
      </a>
      {% endfor %}
    </div>
    <script src="{% static 'js/magicgrid.js' %}"></script>
    {% else %}
    <div class="text-center">
        <h1>No Articles YET!</h1>
    </div>
    {% endif %}

    {% include 'snippets/pagination.html' with page_obj=page_obj %}

    <div style="text-align: center;">
      <a href="{% url 'articleapp:create' %}" class="btn btn-dark rounded-pill mt-3 mb-3 px-3">
        Create Article
      </a>
    </div>

templates/snippets/pagination.html
<div style="text-align: center; margin: 1rem 0;">
    {% if page_obj.has_previous %}
    <a href="?page={{ page_obj.previous_page_number }}"
    class="btn-btn-secondary rounded-pill">
        {{ page_obj.previous_page_number }}
    </a>
    {% endif %}
    <a href="?page={{ page_obj.number }}"
    class="btn btn-secondary rounded-pill active">
        {{ page_ob.number }}
    </a>
    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}"
    class="btn btn-secondary rounded-pill">
        {{ page_obj.next_page_number }}
    </a>
    {% endif %}
</div>